name: lucky_envolope
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_gen: ^5.1.0+1
  flutter_bloc: ^8.1.1
  json_serializable: ^6.5.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  pull_to_refresh: ^2.0.0
  go_router: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  flutter_launcher_icons: 0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/envolopes/
    - assets/images/denominations/
    - assets/icon/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo_logo_up.png"
  min_sdk_android: 21

  
