name: lucky_envolope
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_gen: ^5.4.0
  flutter_bloc: ^8.1.3
  json_serializable: ^6.7.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  pull_to_refresh: ^2.0.0
  go_router: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
#  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/envolopes/
    - assets/images/denominations/
    - assets/icon/
    - assets/logo/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_logo_up.png"
  min_sdk_android: 21

  
